name: haskell

dependencies:
  - base
  - text
  - bytestring
  - hedis
  - managed
  - exceptions
  - containers
  - scotty
  - mtl
  - time
  - random
  - transformers
  - sqlite-simple
  - async
  - tasty
  - stm
  - comonad
  - free

library:
  source-dirs: src
  default-extensions:
    - DeriveFunctor
